### ISSUE TITLE
Quick Setup guide - don't work in some linux systems

### ISSUE THREAD

**Issue by vinimmelo** [ayr-ton/kamu#63]
Specifically in the openSuse and Debian system, the quick setup guide presents problems after the requirements install, i don't tested in more systems but the error occur when trying to do the command 
```shell
python3 manage.py migrate
```
Yeah, just the command "python" won't wortk either on this systems, we need to standard the quick guide or to  avoid this messages, the complete error message is:

`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vinicius/Vinicius/programs/Bucket/kamu/kamu/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/vinicius/Vinicius/programs/Bucket/kamu/kamu/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/vinicius/Vinicius/programs/Bucket/kamu/kamu/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vinicius/Vinicius/programs/Bucket/kamu/kamu/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/vinicius/Vinicius/programs/Bucket/kamu/kamu/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/vinicius/Vinicius/programs/Bucket/kamu/kamu/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework'
`
Any clue about what i have to do in that case?

**Comment by ayr-ton** [comment]
Using the Python3.6 virtual environment as pointed on the README.md should set the Python 3 as default `python`. How are you using virtualenvs?

**Comment by vinimmelo** [comment]
Yeah, i will try on python 3.6.5, currently i am using python 3.7, that could mislead the manage.py. After the test i will update this issue...

**Comment by edersonbadeca** [comment]
@vinimmelo This issue will be closed by the overdue action.
